version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - dnitsch
  - naren-bellala
  ignore:
  - dependency-name: ts-node
    versions:
    - ">= 8.10.a, < 8.11"
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: jest-junit
    versions:
    - 12.0.0
  - dependency-name: hosted-git-info
    versions:
    - 2.8.9
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: handlebars
    versions:
    - 4.7.7
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.3
  - dependency-name: ini
    versions:
    - 1.3.7
  rebase-strategy: disabled
- package-ecosystem: nuget
  directory: "/packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Selenium"
  schedule:
    interval: weekly
    day: sunday
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - estherthetesteramido
  ignore:
  - dependency-name: coverlet.collector
    versions:
    - "> 1.2.0, < 1.3"
  - dependency-name: Selenium.WebDriver.ChromeDriver
    versions:
    - 90.0.4430.2400
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.4
  rebase-strategy: disabled
- package-ecosystem: npm
  directory: "/packages/pact-config"
  schedule:
    interval: weekly
    day: sunday
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ts-jest
    versions:
    - "> 25.5.0, < 25.6"
  - dependency-name: ts-node
    versions:
    - ">= 8.10.a, < 8.11"
  - dependency-name: jest-junit
    versions:
    - 12.0.0
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: hosted-git-info
    versions:
    - 2.8.9
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.3
  rebase-strategy: disabled
- package-ecosystem: npm
  directory: "/packages/scaffolding-cli/templates/test/testcafe"
  schedule:
    interval: weekly
    day: sunday
    timezone: Europe/London
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: eslint
    versions:
    - ">= 7.1.a, < 7.2"
  - dependency-name: prettier
    versions:
    - ">= 2.0.a, < 2.1"
  - dependency-name: testcafe
    versions:
    - "> 1.8.3, < 1.9"
  - dependency-name: typescript
    versions:
    - ">= 3.9.a, < 3.10"
  - dependency-name: prettier
    versions:
    - 2.3.0
  - dependency-name: typescript
    versions:
    - 4.2.4
  - dependency-name: eslint
    versions:
    - 7.27.0
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: axios
    versions:
    - 0.21.1
  rebase-strategy: disabled
- package-ecosystem: npm
  directory: "/packages/scaffolding-cli/templates/test/cypress-typescript-axe-applitools-lighthouse"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@applitools/eyes-cypress"
    versions:
    - 3.21.1
  - dependency-name: axe-core
    versions:
    - 4.2.1
  - dependency-name: cypress-audit
    versions:
    - 0.3.0
  - dependency-name: typescript
    versions:
    - 4.2.4
  - dependency-name: underscore
    versions:
    - 1.13.1
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: node-fetch
    versions:
    - 2.6.1
  rebase-strategy: disabled
- package-ecosystem: npm
  directory: "/packages/scaffolding-cli/templates/test/jest-typescript-sonar"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.12.0
    - 15.12.1
    - 15.3.1
    - 15.6.0
    - 15.6.1
    - 15.9.0
  - dependency-name: babel-jest
    versions:
    - 26.6.3
    - 27.0.1
  - dependency-name: jest-junit
    versions:
    - 12.0.0
    - 12.1.0
  - dependency-name: typescript
    versions:
    - 4.2.4
  - dependency-name: "@types/prompts"
    versions:
    - 2.0.12
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.169
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.12.0
  - dependency-name: hosted-git-info
    versions:
    - 2.8.9
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  rebase-strategy: disabled
- package-ecosystem: npm
  directory: "/packages/scaffolding-cli/templates/test/cypress-typescript-coreui"
  schedule:
    interval: weekly
    day: sunday
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: axe-core
    versions:
    - 4.1.3
    - 4.1.4
    - 4.2.0
    - 4.2.1
  - dependency-name: mocha
    versions:
    - 8.3.1
    - 8.3.2
    - 8.4.0
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: underscore
    versions:
    - 1.13.1
  - dependency-name: typescript
    versions:
    - 4.2.3
    - 4.2.4
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: mochawesome-report-generator
    versions:
    - 5.2.0
  - dependency-name: mochawesome
    versions:
    - 6.2.2
  - dependency-name: cypress-axe
    versions:
    - 0.12.2
  - dependency-name: cypress-audit
    versions:
    - 0.3.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: cypress
    versions:
    - 5.6.0
  rebase-strategy: disabled
- package-ecosystem: maven
  directory: "/packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.cucumber:cucumber-junit
    versions:
    - 6.10.1
    - 6.10.2
    - 6.10.3
    - 6.10.4
  - dependency-name: net.serenity-bdd.maven.plugins:serenity-maven-plugin
    versions:
    - 2.3.31
    - 2.4.1
    - 2.4.2
    - 2.4.20
    - 2.4.21
    - 2.4.24
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: net.serenity-bdd:serenity-rest-assured
    versions:
    - 2.3.31
    - 2.4.1
    - 2.4.2
    - 2.4.20
    - 2.4.21
    - 2.4.24
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: net.serenity-bdd:serenity-screenplay-webdriver
    versions:
    - 2.3.31
    - 2.4.1
    - 2.4.2
    - 2.4.20
    - 2.4.21
    - 2.4.24
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: net.serenity-bdd:serenity-screenplay
    versions:
    - 2.3.31
    - 2.4.1
    - 2.4.2
    - 2.4.20
    - 2.4.21
    - 2.4.24
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: net.serenity-bdd:serenity-junit
    versions:
    - 2.3.31
    - 2.4.1
    - 2.4.2
    - 2.4.20
    - 2.4.21
    - 2.4.24
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.3
  - dependency-name: junit:junit
    versions:
    - 4.13.2
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.12.2
    - 2.12.3
  - dependency-name: org.assertj:assertj-core
    versions:
    - 3.19.0
  rebase-strategy: disabled
